/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/suppliers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List suppliers
         * @description Paged list, optionally filtered by a name search and a supplier type. Page size is capped at 50.
         */
        get: operations["ListSuppliers"];
        put?: never;
        /**
         * Create a supplier with its services
         * @description Validation errors use keys like 'Services[0].Price'. A supplier with the same name in the same city returns 409.
         */
        post: operations["CreateSupplier"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/suppliers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a supplier with its services */
        get: operations["GetSupplierById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/suppliers/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extract a supplier draft from pasted text with AI
         * @description Returns a draft to pre-fill the create form plus warnings keyed like validation errors. Nothing is saved. Text is limited to 20,000 characters and requests to 10 per minute. Returns 503 when AI extraction is not enabled (see /features).
         */
        post: operations["ExtractSupplierDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/features": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Which optional features are enabled */
        get: operations["GetFeatures"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/suppliers/{id}/media/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Step 1 of 3: get a signed URL to upload a photo or video to
         * @description Checks the declared file (JPEG, PNG or WebP images and MP4 or WebM videos; images up to 10 MB, videos up to 100 MB, at most 20 per supplier) and returns a URL valid for 15 minutes. Step 2: send the file to uploadUrl with the given method and headers. Step 3: POST /suppliers/{id}/media with the mediaId.
         */
        post: operations["RequestSupplierMediaUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/suppliers/{id}/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Step 3 of 3: confirm an uploaded photo or video and add it to the supplier
         * @description Verifies the uploaded file's real type and size, then records it. Safe to retry.
         */
        post: operations["ConfirmSupplierMediaUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/suppliers/{id}/media/{mediaId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a photo or video from a supplier's profile */
        delete: operations["DeleteSupplierMedia"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/{mediaId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * View a photo or video
         * @description Redirects to a short-lived signed URL on the object store, which supports range requests for video.
         */
        get: operations["GetMediaFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ConfirmMediaUploadRequest: {
            /** Format: uuid */
            mediaId: string;
            fileName: string;
            contentType: string;
        };
        CreateServiceRequest: {
            name?: string;
            type?: null | components["schemas"]["ServiceType"];
            description?: null | string;
            /** Format: double */
            price?: null | number;
            currency?: string;
            pricingUnit?: null | components["schemas"]["PricingUnit"];
            /** Format: int32 */
            durationMinutes?: null | number;
            /** Format: int32 */
            capacity?: null | number;
        };
        CreateSupplierRequest: {
            name?: string;
            type?: null | components["schemas"]["SupplierType"];
            description?: null | string;
            contactName?: null | string;
            email?: null | string;
            phone?: null | string;
            website?: null | string;
            addressLine?: null | string;
            city?: string;
            country?: string;
            services?: components["schemas"]["CreateServiceRequest"][];
        };
        ExtractionWarning: {
            field: string;
            message: string;
        };
        ExtractSupplierDraftRequest: {
            text: string;
        };
        ExtractSupplierDraftResult: {
            draft: components["schemas"]["CreateSupplierRequest"];
            warnings: components["schemas"]["ExtractionWarning"][];
        };
        FeaturesResponse: {
            aiExtraction: boolean;
        };
        HttpValidationProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
            errors?: {
                [key: string]: string[];
            };
        };
        MediaDto: {
            /** Format: uuid */
            id: string;
            kind: components["schemas"]["MediaKind"];
            fileName: string;
            contentType: string;
            /** Format: int64 */
            sizeBytes: number;
            url: string;
            /** Format: date-time */
            uploadedAt: string;
        };
        /** @enum {unknown} */
        MediaKind: "Image" | "Video";
        MediaUploadTicket: {
            /** Format: uuid */
            mediaId: string;
            /** Format: uri */
            uploadUrl: string;
            method: string;
            headers: {
                [key: string]: string;
            };
            /** Format: date-time */
            expiresAt: string;
        };
        PagedResultOfSupplierSummaryDto: {
            items: components["schemas"]["SupplierSummaryDto"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: int32 */
            totalCount: number;
            /** Format: int32 */
            totalPages?: number;
        };
        /** @enum {unknown} */
        PricingUnit: "PerPerson" | "PerPersonPerNight" | "PerRoomPerNight" | "PerVehicle" | "PerGroup";
        ProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
        };
        RequestUploadBody: {
            fileName: string;
            contentType: string;
            /** Format: int64 */
            sizeBytes: number;
        };
        ServiceDto: {
            /** Format: uuid */
            id: string;
            name: string;
            type: components["schemas"]["ServiceType"];
            description: null | string;
            /** Format: double */
            price: number;
            currency: string;
            pricingUnit: components["schemas"]["PricingUnit"];
            /** Format: int32 */
            durationMinutes: null | number;
            /** Format: int32 */
            capacity: null | number;
            isActive: boolean;
        };
        /** @enum {unknown} */
        ServiceType: "Accommodation" | "Activity" | "Tour" | "Transfer" | "Meal" | "Other";
        SupplierDto: {
            /** Format: uuid */
            id: string;
            name: string;
            type: components["schemas"]["SupplierType"];
            description: null | string;
            contactName: null | string;
            email: null | string;
            phone: null | string;
            website: null | string;
            addressLine: null | string;
            city: string;
            country: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            services: components["schemas"]["ServiceDto"][];
            media: components["schemas"]["MediaDto"][];
        };
        SupplierSummaryDto: {
            /** Format: uuid */
            id: string;
            name: string;
            type: components["schemas"]["SupplierType"];
            city: string;
            country: string;
            email: null | string;
            phone: null | string;
            /** Format: int32 */
            serviceCount: number;
            /** Format: date-time */
            createdAt: string;
            coverImageUrl: null | string;
        };
        /** @enum {unknown} */
        SupplierType: "Accommodation" | "Activity" | "Transport" | "Restaurant" | "Other";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ListSuppliers: {
        parameters: {
            query?: {
                Page?: number;
                PageSize?: number;
                Search?: string;
                Type?: components["schemas"]["SupplierType"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedResultOfSupplierSummaryDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    CreateSupplier: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSupplierRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplierDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetSupplierById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplierDto"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ExtractSupplierDraft: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExtractSupplierDraftRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractSupplierDraftResult"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetFeatures: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeaturesResponse"];
                };
            };
        };
    };
    RequestSupplierMediaUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestUploadBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaUploadTicket"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    ConfirmSupplierMediaUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmMediaUploadRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    DeleteSupplierMedia: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                mediaId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetMediaFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mediaId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Found */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
}
